Store.destroy_all
Product.destroy_all

Store.create address: '200 W. Madison St, Chicago, IL'
Store.create address: '2250 N. Clark St, Chicago, IL'
Store.create address: '333 W. Randolph, Chicago, IL'
Store.create address: '5555 S. Ellis Ave, Chicago, IL'
Store.create address: '1154 S. Clark St, Chicago, IL'
Store.create address: '1101 W. Jackson Blvd, Chicago, IL'
Store.create address: '1940 W. 33rd St, Chicago, IL'
Store.create address: '4466 N Broadway St, Chicago, IL'

Product.create sku: 'B0002F58TG', photo_url: 'http://ecx.images-amazon.com/images/I/61fspjyu4yL._SL1500_.jpg', title: 'Jasmine S35 Acoustic Guitar', description: 'This Amazon Marketplace top-selling acoustic guitar is the perfect instrument for a beginner of any age, or as a second instrument for the seasoned player. From its detailed appointments to the bold acoustic tones it projects, the Jasmine S35 dreadnought guitar is an excellent all around solution for any style of music. This finely crafted instrument is backed by a limited lifetime warranty.'
Product.create sku: 'B0009EU0S4', photo_url: 'http://ecx.images-amazon.com/images/I/41wHcOyZ%2B4L.jpg', title: 'Latin Percussion LPA280 Aspire Bar Chimes', description: 'Great value for any beginning player, these chimes sounds great.'
Product.create sku: 'B00466HM28', photo_url: 'http://ecx.images-amazon.com/images/I/41ZILa2C9ZL.jpg', title: 'Akai Professional Ultra-Portable Keyboard', description: "The Akai Pro MPK mini is an ultra-compact mini-keyboard with an impressive array of buttons, knobs and pads to provide 'hands-on' performance and production control no matter your location. MPK mini strikes the perfect balance between portability and comprehensive software control by melding together the complete control offered in the popular Akai Pro MPK family with the grab-and-go convenience of the LPK25 and LPD8. With a 25-note keyboard, 8 back-lit, MPC-style pads and 8 Q-Link knobs, the MPK mini is the ultimate portable controller to get your music moving.The MPK mini keyboard is ideal for quickly entering notes and phrases into your computer. The velocity-sensitive keys allow you to accurately express dynamics, while accessing different pitch ranges is done instantly through dedicated Octave Up and Down buttons. Create sparkling, staccato leads and driving bass-lines in a variety of time denominations and patterns with MPK mini's built-in Arpeggiator. A Tap-Tempo button gives you the ability to quickly adjust the Arpeggiator clock which is essential if you're looking to stay in sync with a band. A Sustain button holds notes after releasing your hand from the keyboard allowing you the opportunity to easily pound pads and twist knobs, with no pedal required."
Product.create sku: 'B000FMDIXY', photo_url: 'http://ecx.images-amazon.com/images/I/31u3oQFsGwL.jpg', title: 'Evans 2-Sided Practice Pad', description: "RealFeel by Evans 12\" 2-sided pad has a large playing surface that fits inside a standard snare basket, a natural gum feel on one side for realistic stick rebound, and a harder recycled rubber surface on the other for a real workout. RealFeel by Evans practice pads are the most popular practice pad option available. Featuring a natural gum rubber playing surface with a dark gray fabric finish which resists wear and tear, RealFeel by Evans practice pads provide the best practice substitute to an acoustic drum. A variety of models are available to suit individual practice requirements. For over 40 years, Evans has been a pioneer of drum head manufacturing and design. Known for innovative designs such as EMAD, EC2S, and the Hydraulic series, Evans drum heads are made in the USA in a state of the art manufacturing facility. Acquired in 1996 by D’Addario and Company, the global leader in musical instrument accessories, the Evans brand is synonymous with quality and consistency."
Product.create sku: 'B00HVLUR86', photo_url: 'http://ecx.images-amazon.com/images/I/815OQlSZfkL._SL1500_.jpg', title: 'Audio-Technica ATH-M50x Professional Studio Monitor Headphones', description: "As the most critically acclaimed model in the M-Series line, the ATH-M50 is praised by top audio engineers and pro audio reviewers year after year. Now, the ATH-M50x professional monitor headphones feature the same coveted sonic signature, with the added feature of detachable cables. From the large aperture drivers, sound isolating earcups and robust construction, the M50x provides an unmatched experience for the most critical audio professionals."
Product.create sku: 'B0002CZUV0', photo_url: 'http://ecx.images-amazon.com/images/I/71wqFucRo3L._SL1500_.jpg', title: 'Epiphone LP Special II Les Paul Electric Guitar, Vintage Sunburst', description: "What's so special about the Epiphone Les Paul Special II Electric Guitar? The super-low price for starters and that's not all. It gives you all the essential elements of a Les Paul. Made with a mahogany body, bolt-on mahogany neck, smooth 22-fret rosewood fingerboard, this baby is every bit as handsome as its uptown cousins. Features 700T/650R open-coil humbucking pickups that deliver long, singing sustain and true Les Paul tones. The LockTone Tune-O-Matic bridge and stopbar tailpiece add more sustain and make string changing easier. Limited lifetime warranty."
Product.create sku: 'B00COC61LO', photo_url: 'http://ecx.images-amazon.com/images/I/811nlTQ18xL._SL1500_.jpg', title: 'Ion Audio Max LP 3-Speed Belt Drive Wooden DJ Turntable with Built-In Speakers', description: "Listen, connect, and convert with ION’s Max LP, a simple all-in-one turntable that makes it easy to enjoy your records and convert them to digital music files on your computer. With Max LP, transferring your 33 1/3, 45, and 78 RPM records to a Mac or PC is easy: just connect Max LP to your computer with the included USB cable to get started. ION’s exclusive EZ Vinyl/Tape Converter software guides you through the steps. Plus, you can convert from other audio sources, like a cassette player, using the 1/8-inch auxiliary input."
Product.create sku: 'B00DWJ1WYY', photo_url: 'http://ecx.images-amazon.com/images/I/61L2Qv2JoyL._SL1000_.jpg', title: 'Yamaha DGX650B Digital Piano', description: "The DGX-650 is Yamaha’s newest ensemble digital piano to feature a variety of interactive features that make learning, playing and sharing music fun for everyone. Acoustic piano touch and tone come first via the Graded Hammer Standard action and PureCF sampling, which includes recordings of a Yamaha concert grand piano. A weighted action with heavier touch in the low end and lighter touch in the high end, just like the hammers inside an acoustic piano. Great for the aspiring pianist, practicing on the GHS action builds the proper finger technique for when the time comes to perform on an acoustic piano."
